name: Flutter Nightly m4x Build

on:
  schedule:
    # schedule build every night
    - cron: "10 0 1 * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build_m4x.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly"
